apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ThreeApi
namespace: staging
bases:
  - ../../base
commonAnnotations:
  app: ThreeApi
  backstage.io/kubernetes-id: "ThreeApi"
commonLabels:
  app: ThreeApi
  backstage.io/kubernetes-id: "ThreeApi"
patchesStrategicMerge:
  - configmap_patch.yaml
  - deployment_patch.yaml